### ISSUE TITLE
Dockerfile for requestbox

### ISSUE THREAD

**Issue by colthreepv** [kevinastone/requestbox#2]
Hi, I am trying to create a Dockerfile for requestbox, to build it and host it easily.

I have zero experience with erlang/elixir/phoenix platform though, so It's getting a bit messy.
**EDIT:** current Dockerfile & docker-compose: https://gist.github.com/colthreepv/7518f3a2124489c55a2d07593015f6cc

This is a non-definitive version, there are way too many RUN command(s), they will get flattened as soon as everything works.

The problem at the moment is splitting the compiling part and the `ecto.create` that initializes the database, can you help me do that?
I would like to compile during the build, but then execute the first migration manually, or via docker-compose

**Comment by kevinastone** [comment]
Is your database on the same docker container?  Normally it's setup to use postgres in prod (and sqlite in dev) using the env $DATABASE_URL.  I would expect this to be a linked container, so you'll be unable to run `ecto.create` on build.

https://github.com/kevinastone/requestbox/blob/master/config/prod.exs#L24-L27

**Comment by kevinastone** [comment]
I would use a docker-compose config to setup the dependent containers such as postgres.

**Comment by colthreepv** [comment]
Yes, exactly, I want to do that, that's why I would like to compile dependencies while executing Dockerfile, but not execute migrations, I noticed that `ecto.create` does both (compile then execute migrations).

My plan to create a separate `docker-compose.yml` that will hande the postgres database as well as the one-time command to create migrations and only then execute `phoenix.server`

**Comment by kevinastone** [comment]
I think you can just use `mix build` to compile separately.

**Comment by colthreepv** [comment]
Thanks for your feedback, I'll try more.. seems (not sure 100% as it didn't run, yet) that `mix compile` would do the job, `mix build` or `mix release` hangs at the end of the process reporting:

```
Generated phoenix_ecto app
==> requestbox
** (Mix) Cannot execute task because the project was not yet compiled. When build_embedded is set to true, "MIX_ENV=prod mix compile" must be explicitly executed
The command '/bin/sh -c cd requestbox-${BRANCH} && mix local.rebar && mix release' returned a non-zero code: 1
```

**Comment by colthreepv** [comment]
Running requestbox in dev mode is blissfully easy, but trying to make it run in production has some issues, especially coupled with Docker, that I think only you can fix.

Referring to the previous comment, trying to use `MIX_ENV=prod mix compile` breaks [configuration loading](https://github.com/kevinastone/requestbox/blob/master/config/config.exs#L27-L29) in an ugly manner

I am not even sure that environment variable is needed as it is.
Anyway I think the gist linked at the start is a nice bootstrap, maybe you can complete this if you have the time
