### ISSUE TITLE
npm install is failing because of missing package.json

### ISSUE THREAD

**Issue by mbaeuerle** [kevinastone/requestbox#7]
When trying to install the npm dependencies I get the error that the `package.json` is missing. And indeed it's not included in the repo.

**Comment by kevinastone** [comment]
It's under `assets` to match the Phoenix 1.3 layout:
https://gist.github.com/chrismccord/71ab10d433c98b714b75c886eff17357

I'll update the Readme to account for the new `package.json` location

**Comment by kevinastone** [comment]
Fixed
